name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - os
  - spender
  - pip:
    - datasets
    - torch
    - torchvision
    - lightning
    - pl_bolts
    - numpy
    - tqdm
    - scipy
    - scikit-learn
    - matplotlib
    - seaborn
